apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-demo
  #namespace: default
  namespace: default 
spec:
  selector:
    matchLabels:
      app: php-demo
  template:
    metadata:
      labels:
        app: php-demo
    spec:
      containers:
      - image: swr.ap-southeast-2.myhuaweicloud.com/wisanu/php-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        command:
          - sleep
        args:
          - '1000'
        name: php-demo
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
